### ISSUE TITLE
Formatting improvements

### ISSUE THREAD

**Issue by connorshea** [AaronC81/sord#30]
**Is your feature request related to a problem? Please describe.**
I'd like to see the formatting of code output by sord be improved.

I know this is mentioned in #13, but I wanted to have a separate issue for it - plus I have another suggestion to add to what's mentioned in that issue.

**Describe the solution you'd like**
Generally, sord outputs code that looks like the following:

```ruby
# typed: strong
module Discordrb
  sig { params(one_id: T.untyped, other: T.untyped).void }
  def self.id_compare(one_id, other); end
  sig { params(msg: String).returns(T::Array[String]) }
  def self.split_message(msg); end
module API
  sig { returns(String) }
  def api_base(); end
  sig { returns(String) }
  def self.api_base(); end
module User
  sig { params(token: T.untyped, user_id: T.untyped).void }
  def resolve(token, user_id); end
  sig { params(token: T.untyped, user_id: T.untyped).void }
  def self.resolve(token, user_id); end
end
end
end

```

However, I'd like it to do three main things to make the generated rbi files more readable:

- Linebreaks between signature/method pairs
- Linebreaks between modules/classes
- Indent the code properly when nesting modules/classes

Like this:
```ruby
# typed: strong
module Discordrb
  sig { params(one_id: T.untyped, other: T.untyped).void }
  def self.id_compare(one_id, other); end

  sig { params(msg: String).returns(T::Array[String]) }
  def self.split_message(msg); end

  module API
    sig { returns(String) }
    def api_base(); end

    sig { returns(String) }
    def self.api_base(); end

    module User
      sig { params(token: T.untyped, user_id: T.untyped).void }
      def resolve(token, user_id); end

      sig { params(token: T.untyped, user_id: T.untyped).void }
      def self.resolve(token, user_id); end
    end
  end
end
```

I also wanted to suggest that the signature output by sord use block syntax after a certain number of parameters is reached (probably 4 or 5 by default?), preferably with this number being configurable using a command line flag.

e.g. instead of this:

```ruby
sig { params(one: T.untyped, two: T.untyped, three: T.untyped, four: T.untyped, five: T.untyped).void }
def self.id_compare(one, two, three, four, five); end
```

sord would output this:

```ruby
sig do
  params(
    one: T.untyped,
    two: T.untyped,
    three: T.untyped,
    four: T.untyped,
    five: T.untyped
  ).void
end
def self.id_compare(one, two, three, four, five); end
```

**Describe alternatives you've considered**
Running an auto-formatter rufo or rubocop on the code after its been generated is an option, and while it fixes the indentation problem, unfortunately neither has a concept of signatures so they don't really do sensible things when formatting code with them.

Rufo, for example, seems to group them in pairs of three or one?

```ruby
module Discordrb
  sig { params(one_id: T.untyped, other: T.untyped).void }
  def self.id_compare(one_id, other); end
  sig { params(msg: String).returns(T::Array[String]) }
  def self.split_message(msg); end

  module API
    sig { returns(String) }

    def api_base(); end

    sig { returns(String) }
    def self.api_base(); end
    sig { params(value: String).void }

    def api_base=(value); end

    sig { params(value: String).void }
    def self.api_base=(value); end
    sig { returns(String) }

    def cdn_url(); end

    module User
      sig { params(token: T.untyped, user_id: T.untyped).void }

      def resolve(token, user_id); end
    end
  end
end
```

**Comment by nbulaj** [comment]
Hi  @AaronC81 !

I tried Sord and found it pretty useful for my project with good YARD coverage. But agree with @connorshea, it would be great if it can generate formatted output with separated sig-def. LMK if I can help somehow or need to test if this feature already added to the project

**Comment by AaronC81** [comment]
@connorshea, @nbulaj - it would be great if you could try out the `formatting` branch and let me know how you find it!
`
This will break parameters onto their own lines if the number of parameters is at least `--break-params` (default 4.)

As an example, before:

```ruby
sig { params(kind: Symbol, msg: String, item: YARD::CodeObjects::Base, indent_level: Integer).void }
def self.invoke_hooks(kind, msg, item, indent_level = 0); end
```

After:

```ruby
sig do
  params(
    kind: Symbol, 
    msg: String, 
    item: YARD::CodeObjects::Base, 
    indent_level: Integer
  ).void
end
def self.invoke_hooks(kind, msg, item, indent_level = 0); end
```

**Comment by nbulaj** [comment]
@AaronC81 params is great, but I totally agree with Connor - we need also linebreaks between signature/method pairs and module/classes. Because in other case it looks like a mess.

You can check the RBI file for my gem that I generated using `sord`, but with manually formatted to be a human readable: https://github.com/nbulaj/alpha_card/blob/3f8d6922c38258c73bf5b399d3fe412bd1155aac/defs.rbi (from https://github.com/nbulaj/alpha_card/pull/3 )

**Comment by AaronC81** [comment]
Oops, I missed this from the issue! Line breaks between items are now implemented on the `formatting` branch, so give it another go and see how it works for you.

**Comment by connorshea** [comment]
Would it be insane to also have logic to remove the linebreak before an `end`? 🤔  Like, when you reach the `end` it'd remove the most recent item. (maybe add a check to make sure the most recent item in the array is a blank string, for safety?)

I haven't run the formatter yet, but I assume this is what it outputs:

```ruby
class ClassName
  module ModuleName
    sig { #whatever }
    def method(); end

    sig { #whatever }
    def method(); end

  end
end
```

And this is what it would output ideally:

```ruby
class ClassName
  module ModuleName
    sig { #whatever }
    def method(); end

    sig { #whatever }
    def method(); end
  end
end
```

**Comment by connorshea** [comment]
Also we should probably have tests for this :)

**Comment by AaronC81** [comment]
@connorshea - it does actually output your "ideal" output currently. It inserts empty lines _before_ each item, except on the first one, which results in the same thing. (I've just noticed an issue that comments are before the blank line, however - I'll look into fixing this.)

And yep, tests would definitely be a good addition. There's no suite for the RBI generator yet but I can work on that shortly.

**Comment by AaronC81** [comment]
With regards to testing, I'm not sure which method is best to approach it.

Should the suite generate 'stub' YARD registries (if that's even possible), run Sord on them, and check the output? Is there a better way?

**Comment by connorshea** [comment]
There seems to be a bug where there are extra linebreaks sometimes (tested with discordrb):

```ruby
    sig { void }
    def online(); end


    sig { void }
    def idle(); end


    sig { void }
    def dnd(); end
```

Aliases, maybe?

**Comment by connorshea** [comment]
Yup, pretty sure it's aliases. The `add_blank` method comes before the alias skipper.

**Comment by AaronC81** [comment]
Good catch, should be fixed now!

There seems to be an issue with the indentation of some log comments too:

```ruby
  # sord infer - VoiceBot was unresolvable, inferred it to be Discordrb::Voice::VoiceBot
    sig { returns(T::Hash[Integer, Discordrb::Voice::VoiceBot]) }
    def voices(); end

  # sord warn - Voice::VoiceBot was unresolvable
    sig { params(thing: T.any(Channel, Server, Integer)).returns(T.nilable(Voice::VoiceBot)) }
    def voice(thing); end
```

**Comment by connorshea** [comment]
It seems my changes to indentation didn't consider that some log statements come from the type converter, which doesn't currently have any `indent_level` information, so some of the comments aren't indented properly.

And I see you've just found that issue too :D

**Comment by connorshea** [comment]
Opened #46 to fix that

**Comment by connorshea** [comment]
Also, did you push the change that fixes the linebreaks caused by aliases? I'm still seeing the problem.

**Comment by AaronC81** [comment]
Whoops, guess who typed `git push origin master` into discordrb and not Sord...

Should _actually_ be on master now!

**Comment by connorshea** [comment]
I think this issue is pretty much fixed now :D The only other thing I'd suggest is potentially adding linebreaks after the last `extend` or `include` for a class/module.

Current:

```ruby
class Integration
  extend Discordrb::IDObject
  sig { returns(String) }
  def name(); end
end
```

Ideal:

```ruby
class Integration
  extend Discordrb::IDObject

  sig { returns(String) }
  def name(); end
end
```

**Comment by connorshea** [comment]
It seems some `infer` comments in bundler's rbi are indented incorrectly :/

**Comment by AaronC81** [comment]
Unless I've missed any of the changes mentioned here, they should all be on the `formatting` branch now!

I see the issue with incorrect comment indentation in Bundler; this class is especially funky:

```ruby
    class VersionConflict < Bundler::Molinillo::ResolverError
      extend Bundler::Molinillo::Delegates::SpecificationProvider
  # sord warn - Resolution::Conflict wasn't able to be resolved to a constant in this project
      sig { returns(T::Hash<String, Resolution::Conflict>) }
      def conflicts(); end

      # sord warn - SpecificationProvider wasn't able to be resolved to a constant in this project
      sig { returns(SpecificationProvider) }
      def specification_provider(); end

  # sord warn - Resolution::Conflict wasn't able to be resolved to a constant in this project
      # sord warn - SpecificationProvider wasn't able to be resolved to a constant in this project
      sig { params(conflicts: T::Hash<String, Resolution::Conflict>, specification_provider: SpecificationProvider).returns(VersionConflict) }
      def initialize(conflicts, specification_provider); end

      sig { params(opts: Hash).returns(String) }
      def message_with_trees(opts = {}); end

      sig { params(dependency: Object).returns(T::Array[Object]) }
      def search_for(dependency); end

      sig { params(specification: Object).returns(T::Array[Object]) }
      def dependencies_for(specification); end

      sig { params(requirement: Object, activated: DependencyGraph, spec: Object).returns(T::Boolean) }
      def requirement_satisfied_by?(requirement, activated, spec); end

      sig { params(dependency: Object).returns(String) }
      def name_for(dependency); end

      sig { returns(String) }
      def name_for_explicit_dependency_source(); end

      sig { returns(String) }
      def name_for_locking_dependency_source(); end

  # sord infer - Conflict was resolved to Bundler::Molinillo::Resolver::Resolution::Conflict
      sig { params(dependencies: T::Array[Object], activated: DependencyGraph, conflicts: T::Hash<String, T::Array[Bundler::Molinillo::Resolver::Resolution::Conflict]>).returns(T::Array[Object]) }
      def sort_dependencies(dependencies, activated, conflicts); end

      sig { params(dependency: Object).returns(T::Boolean) }
      def allow_missing?(dependency); end

      sig { returns(T.untyped) }
      def with_no_such_dependency_error_handling(); end
    end
```

**Comment by AaronC81** [comment]
This is now fixed on the `formatting` branch - my implementation of #43 didn't pass `indent_level` to its recursive `yard_to_sorbet` calls.

**Comment by AaronC81** [comment]
Merged!
